### ISSUE TITLE
The solar-project/solar-master built with missing apt-get update step

### ISSUE THREAD

**Issue by bogdando** [Mirantis/solar#246]
The issue is what the command 'sudo apt-get install libguestfs-tools' fails, unless I do 'sudo apt-get update' on a fresh node provisioned by vagrant

**Comment by bogdando** [comment]
I figured out that the image is obsolete. I fixed this issue for my custom image bogdando/solar-master

**Comment by loles** [comment]
We will fix it with APT resource. 
As a workaround we may add update to node.run action

**Comment by bogdando** [comment]
The fix is https://github.com/Mirantis/solar/pull/249

**Comment by bogdando** [comment]
With the packer image built from the fix, the libguestfs-tools works now
