### ISSUE TITLE
Random 401 Unauthorized errors for mysql backend for keystone

### ISSUE THREAD

**Issue by bogdando** [Mirantis/solar#252]
When deployed with default MySQL backend, the auth requests are sporadically failing. Sometimes it is 5/10 and sometimes 9/10 keystone CLI failures in a raw.

The w/o is to configure memcached backend (I verified there would be no issues anymore)

**Comment by loles** [comment]
do you have traceback?

**Comment by loles** [comment]
Fixed after moving to sql backend for tokens
